### ISSUE TITLE
NullPointerException in 10.6.4.0 (43650) when fast forwarding 

### ISSUE THREAD

**Issue by Crystal-RainSlide** [forkgram/TelegramAndroid#231]
Right after fast forwarding finished.

log:
> https://paste.crdroid.net/wQLpzl
``` log
time: 1707872060355
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.telegram.ui.Components.UndoView.showWithAction(long, int, java.lang.Object, java.lang.Object, java.lang.Runnable, java.lang.Runnable)' on a null object reference
stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.telegram.ui.Components.UndoView.showWithAction(long, int, java.lang.Object, java.lang.Object, java.lang.Runnable, java.lang.Runnable)' on a null object reference
	at org.telegram.ui.ChatActivity$5.onSend(ChatActivity.java:1141)
	at org.telegram.ui.Components.ShareAlert.sendInternal(ShareAlert.java:2287)
	at org.telegram.ui.Components.ShareAlert.lambda$new$12$org-telegram-ui-Components-ShareAlert(ShareAlert.java:1543)
	at org.telegram.ui.Components.ShareAlert$$ExternalSyntheticLambda22.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7658)
	at android.view.View.performClickInternal(View.java:7635)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30185)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8244)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**Comment by kyoto44** [comment]
Same

**Comment by fluffy11lol** [comment]
Same

**Comment by fluffy11lol** [comment]
@23rd
