### ISSUE TITLE
Unable to upgrade app : DISPLAY_NAME column is null

### ISSUE THREAD

**Issue by Revdep** [forkgram/TelegramAndroid#233]
That's the full error :

`com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor$BadContentProviderException: DISPLAY_NAME column is null
	at com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor.name(ContentUriFileDescriptor.java:30)
	at com.aefyr.sai.model.apksource.DefaultApkSource.getApkName(DefaultApkSource.java:42)
	at com.aefyr.sai.model.apksource.SignerApkSource.getApkName(SignerApkSource.java:64)
	at com.aefyr.sai.model.apksource.SignerApkSource.nextApk(SignerApkSource.java:46)
	at com.aefyr.sai.model.apksource.FilterApkSource.nextApk(FilterApkSource.java:25)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.install(RootlessSaiPackageInstaller.java:93)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.lambda$enqueueSession$0$RootlessSaiPackageInstaller(RootlessSaiPackageInstaller.java:70)
	at com.aefyr.sai.installer2.impl.rootless.-$$Lambda$RootlessSaiPackageInstaller$ivyAcunEgIkYlu_dB2vN6MOWZPU.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
`

There is a solution to this?
I'm using CalyxOS(A14) on pixel 6. I get this error since 3 forkgram build when I was In a different build of calyx too.
I can't get what's the problem.

**Comment by fbobraga** [comment]
Seems to be related: the **app name** here (and in several mobiles I've installer the app, with LOS or stock ROM) is **"org.forkgram.<something i can't read>"**, and in the share menu the application has **no icon** (seems like the Android App defalt icon) - screenshots (on a Moto G14 with stock ROM) below:

![Screenshot_20240225-144624~2](https://github.com/forkgram/TelegramAndroid/assets/3438006/63b388a1-b531-42b7-9f12-957fd1436c38)

![Screenshot_20240225-144708~2](https://github.com/forkgram/TelegramAndroid/assets/3438006/fb5d6f1d-de87-4a38-90c5-ed6943f9ef40)

* seems that some metadata is missing in application description
* seems related to https://github.com/forkgram/TelegramAndroid/issues/97 https://github.com/forkgram/TelegramAndroid/issues/103 and https://github.com/forkgram/TelegramAndroid/issues/110

**Comment by ArenaL5** [comment]
Duplicate of #207
