### ISSUE TITLE
[Bug] App crashes on 10.9.9.0

### ISSUE THREAD

**Issue by astravexton** [forkgram/TelegramAndroid#270]
Used the app for a while and updated to 10.9.9.0 but now it crashes.

Nothing Phone(1), Android 14

```FATAL EXCEPTION: main
Process: org.forkclient.messenger.beta, PID: 32335
java.lang.RuntimeException: Unable to create service org.telegram.messenger.NotificationsService: java.lang.IllegalArgumentException: org.forkclient.messenger.beta: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4733)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2295)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8291)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:557)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
Caused by: java.lang.IllegalArgumentException: org.forkclient.messenger.beta: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:6587)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:551)
	at android.app.PendingIntent.getActivity(PendingIntent.java:532)
	at android.app.PendingIntent.getActivity(PendingIntent.java:496)
	at org.telegram.messenger.NotificationsService.onCreate(NotificationsService.java:37)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4720)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:5454)
	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5397)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3260)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2798)
	at android.os.Binder.execTransactInternal(Binder.java:1352)```

**Comment by astravexton** [comment]
![vlcsnap-2024-09-13-01h18m21s757](https://github.com/user-attachments/assets/4aea7e6f-9a23-454d-846c-e0a89a0323da)

It seems to be caused by this popup, I'm unable to do anything since the app just closes, and Fork Client is already set to draw over other apps

**Comment by Ziries** [comment]
I'm having the same issue on my end

**Comment by astravexton** [comment]
https://github.com/forkgram/TelegramAndroid/commit/68d05b504dd12fb310b497e2b8f0ab2e6ec7f49f it seems like this commit broke it? Currently no way around it other than code changes

**Comment by sm131313** [comment]
Same issue here. Is it possible to sideload older version without losing secret chats data?

**Comment by Ziries** [comment]
A quick patch should fix it and keep secret chats intact. The question really is more, when will it get pushed out?

**Comment by xxxsskxxx** [comment]
Receiving the same crash 

Pixel 6 LOS Sept 24
10.9.9.0

**Comment by i1r** [comment]
Same 
Android 14

**Comment by 23rd** [comment]
Can someone please check out this test build from here (debug one)?
https://github.com/forkgram/TelegramAndroid/actions/runs/10847055329

If no one responds within an hour, I'll have to release a public version.

**Comment by astravexton** [comment]
> Can someone please check out this test build from here (debug one)? https://github.com/forkgram/TelegramAndroid/actions/runs/10847055329
> 
> If no one responds within an hour, I'll have to release a public version.

Was sleeping so couldn't test in time, but the public version works fine, thank you <3

**Comment by 23rd** [comment]
> Is it possible to sideload older version without losing secret chats data?

@sm131313 Were you able to save the secret chats?

**Comment by sm131313** [comment]
> > Is it possible to sideload older version without losing secret chats data?
> 
> @sm131313 Were you able to save the secret chats?

I never attempted as didn't want to risk since my device is not rooted. 
I waited for the updated version instead and now all works. 

It would be good to know for future if it would be possible in case similar situation happens again.

**Comment by 23rd** [comment]
> now all works.

Good to hear.

> It would be good to know for future if it would be possible in case similar situation happens again.

Unfortunately it is not possible.

**Comment by nos1609** [comment]
> Can someone please check out this test build from here (debug one)? https://github.com/forkgram/TelegramAndroid/actions/runs/10847055329
> 
> If no one responds within an hour, I'll have to release a public version.

Worked like a charm for me, asking for a full-screen overlay on A14

**Comment by astravexton** [comment]
Going to close this since public release works now, thanks for the quick app update :)
